# Feature Engineering: P2

In [1]:
# Import libraries 
import numpy as np 
import pandas as pd 
import scipy as sp 
import os 
import sys
import matplotlib.pyplot as plt 

# Setup system configuration for file management
sys.path.append(os.path.join(".."))

## Feature Engineering: Approach

- Feature Encoding: 2 binary features
- Feature Transformation

## Feature Encoding: Binary Features

In [2]:
# Import functionalities 
from scripts.data_collection import DataLoader
from scripts.features_utils import FeatureEncoder

In [3]:
# Retrieve directory
dir = r"C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data"
data_folder_list = os.listdir(dir)
files = os.listdir(os.path.join(dir, "processed"))
print(f"Files: {files}")

#  Load the dataset
dataloader = DataLoader(folder="processed")
dataset = dataloader.collect(filename="laptop_price_ds_v3.csv")
dataset

Files: ['laptop_price_ds_v2.csv', 'laptop_price_ds_v3.csv']

,Brand,Processor_brand,Processor_name,Ram_gb,Ssd,Hdd,Os,Os_bit,Graphic_card_gb,Weight,Warranty,Touchscreen,Msoffice,Price,Number of ratings,Number of reviews
0,ASUS,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,34649,3,0
1,Lenovo,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,38999,65,5
2,Lenovo,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,39999,8,1
3,ASUS,Intel,Core i5,8,512,0,Windows,32,2,Casual,1,No,No,69990,0,0
4,ASUS,Intel,Celeron Dual,4,512,512,Windows,64,0,Casual,1,No,No,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,0,Casual,1,No,No,135990,0,0
797,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,0,Casual,1,No,No,144990,0,0
798,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,4,Casual,1,No,No,149990,0,0
799,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,4,Casual,1,No,No,142990,0,0
800,Lenovo,AMD,Ryzen 5,8,512,0,DOS,64,0,ThinNlight,1,No,No,57490,18,4

Binary Encoding

In [4]:
# Check the diagnostic dataset
diag_dataloader = DataLoader("diagnostics")
diagnostic_ds = diag_dataloader.collect(filename="diagnostic_cat_ds_v1.csv")
diagnostic_ds

,FeatureNames,DataTypes,NullValues,NumDistinctValues,UniqueValues,CategoricalType,Cardinality
0,Brand,object,0,8,['ASUS' 'Lenovo' 'acer' 'Avita' 'HP' 'DELL' 'M...,Nominal,Low
1,Processor_brand,object,0,3,['Intel' 'AMD' 'M1'],Nominal,Low
2,Processor_name,object,0,11,['Core i3' 'Core i5' 'Celeron Dual' 'Ryzen 5' ...,Nominal,Medium
3,Os,object,0,3,['Windows' 'DOS' 'Mac'],Nominal,Low
4,Weight,object,0,3,['Casual' 'ThinNlight' 'Gaming'],Nominal,Low
5,Touchscreen,object,0,2,['No' 'Yes'],Binary,Low
6,Msoffice,object,0,2,['No' 'Yes'],Binary,Low

In [5]:
dataset[["Touchscreen", "Msoffice"]]

    Touchscreen Msoffice
0            No       No
1            No       No
2            No       No
3            No       No
4            No       No
..          ...      ...
796          No       No
797          No       No
798          No       No
799          No       No
800          No       No

[801 rows x 2 columns]

In [6]:
# Transform the binary features 
binary_encoder = FeatureEncoder(dataset, "BinaryEncoding")
dataset["Touchscreen"] = binary_encoder.transform("Touchscreen")
dataset["Msoffice"] = binary_encoder.transform("Msoffice")

Other encoding method: BinaryEncoding
Binary Encoding is succesful for Feature Touchscreen
Other encoding method: BinaryEncoding
Binary Encoding is succesful for Feature Msoffice

In [ ]:
dataset[["Touchscreen", "Msoffice"]]

0      0
1      0
2      0
3      0
4      0
      ..
796    0
797    0
798    0
799    0
800    0
Name: Touchscreen, Length: 801, dtype: int64